function E = energyLevel(in1,in2,in3)
%energyLevel
%    E = energyLevel(IN1,IN2,IN3)

%    This function was generated by the Symbolic Math Toolbox version 9.3.
%    04-Aug-2025 16:50:43

alpha = in1(3,:);
d_f = in3(9,:);
d_l = in3(8,:);
dalpha = in1(7,:);
dl = in1(8,:);
dx = in1(5,:);
dy = in1(6,:);
g = in3(2,:);
k_h = in3(14,:);
k_l = in3(15,:);
l = in1(4,:);
l_0 = in3(3,:);
m = in3(1,:);
m_f = in3(5,:);
m_l = in3(4,:);
phi_0 = in3(11,:);
theta_f = in3(7,:);
theta_l = in3(6,:);
y = in1(2,:);
t2 = alpha+phi_0;
t3 = dalpha.^2;
t6 = -l;
t7 = -m;
t4 = cos(t2);
t5 = sin(t2);
t8 = d_f+t6;
t9 = m_f+m_l+t7;
E = (t3.*theta_f)./2.0+(t3.*theta_l)./2.0+(alpha.^2.*k_h)./2.0+(m_f.*((dx+dl.*t5-dalpha.*t4.*t8).^2+(-dy+dl.*t4+dalpha.*t5.*t8).^2))./2.0+(m_l.*((dx+d_l.*dalpha.*t4).^2+(dy+d_l.*dalpha.*t5).^2))./2.0-(t9.*(dx.^2+dy.^2))./2.0+(k_l.*(l-l_0).^2)./2.0+g.*m_l.*(y-d_l.*t4)+g.*m_f.*(y+t4.*t8)-g.*t9.*y;
end
