function out1 = forces(in1,in2,in3)
%FORCES
%    OUT1 = FORCES(IN1,IN2,IN3)

%    This function was generated by the Symbolic Math Toolbox version 9.3.
%    04-Aug-2025 16:50:42

alpha = in1(3,:);
d_f = in3(9,:);
d_l = in3(8,:);
dalpha = in1(7,:);
dl = in1(8,:);
g = in3(2,:);
k_h = in3(14,:);
k_l = in3(15,:);
l = in1(4,:);
l_0 = in3(3,:);
m = in3(1,:);
m_f = in3(5,:);
m_l = in3(4,:);
phi_0 = in3(11,:);
theta_f = in3(7,:);
theta_l = in3(6,:);
u_h = in2(1,:);
u_l = in2(2,:);
xi_h = in3(12,:);
xi_l = in3(13,:);
t2 = alpha+phi_0;
t3 = dalpha.^2;
t6 = -l;
t4 = cos(t2);
t5 = sin(t2);
t7 = d_f+t6;
out1 = [dalpha.*dl.*m_f.*t4.*-2.0-d_f.*m_f.*t3.*t5+d_l.*m_l.*t3.*t5+l.*m_f.*t3.*t5;-g.*m-dalpha.*dl.*m_f.*t5.*2.0+d_f.*m_f.*t3.*t4-d_l.*m_l.*t3.*t4+m_f.*t3.*t4.*t6;u_h-alpha.*k_h-g.*t5.*(-d_f.*m_f+d_l.*m_l+l.*m_f)-dalpha.*xi_h.*sqrt(k_h.*(theta_f+theta_l+m_f.*(d_f+l_0).^2+d_l.^2.*m_l)).*2.0+dalpha.*dl.*m_f.*t7.*2.0;u_l-k_l.*(l-l_0)+g.*m_f.*t4-m_f.*t3.*t7-dl.*xi_l.*sqrt(k_l.*(m-m_f)).*2.0];
end
