function M = massMatrix(in1,in2)
%massMatrix
%    M = massMatrix(IN1,IN2)

%    This function was generated by the Symbolic Math Toolbox version 9.3.
%    04-Aug-2025 16:50:42

alpha = in1(3,:);
d_f = in2(9,:);
d_l = in2(8,:);
l = in1(4,:);
m = in2(1,:);
m_f = in2(5,:);
m_l = in2(4,:);
phi_0 = in2(11,:);
theta_f = in2(7,:);
theta_l = in2(6,:);
t2 = d_f.*m_f;
t3 = d_l.*m_l;
t4 = alpha+phi_0;
t5 = l.*m_f;
t6 = cos(t4);
t7 = sin(t4);
t8 = -t2;
t9 = m_f.*t6;
t10 = m_f.*t7;
t12 = t3+t5+t8;
t11 = -t9;
t13 = t6.*t12;
t14 = t7.*t12;
M = reshape([m,0.0,t13,t10,0.0,m,t14,t11,t13,t14,theta_f+theta_l+d_f.*t2+d_l.*t3-l.*t2.*2.0+l.*t5,0.0,t10,t11,0.0,m_f],[4,4]);
end
