function event_td = event(in1,in2,in3)
%EVENT
%    EVENT_TD = EVENT(IN1,IN2,IN3)

%    This function was generated by the Symbolic Math Toolbox version 9.3.
%    09-Oct-2025 15:29:26

alpha = in1(4,:);
l = in1(5,:);
phi = in1(3,:);
r_f = in3(11,:);
y = in1(2,:);
event_td = -r_f+y-l.*cos(alpha+phi);
end
