function event_nadir = event(in1,in2,in3)
%EVENT
%    EVENT_NADIR = EVENT(IN1,IN2,IN3)

%    This function was generated by the Symbolic Math Toolbox version 24.2.
%    2025-10-30 15:47:00

dl = in1(4,:);
event_nadir = -dl;
end
