function jump_nadir = jump(in1,in2,in3)
%JUMP
%    JUMP_NADIR = JUMP(IN1,IN2,IN3)

%    This function was generated by the Symbolic Math Toolbox version 24.2.
%    2025-10-30 15:47:00

alpha = in1(1,:);
dalpha = in1(3,:);
dl = in1(4,:);
l = in1(2,:);
jump_nadir = [alpha;l;dalpha;dl];
end
