function e_S = event(in1,in2,in3)
%EVENT
%    e_S = EVENT(IN1,IN2,IN3)

%    This function was generated by the Symbolic Math Toolbox version 9.3.
%    04-Aug-2025 16:50:43

alpha = in1(3,:);
l = in1(4,:);
phi_0 = in3(11,:);
r_f = in3(10,:);
y = in1(2,:);
e_S = -r_f+y-l.*cos(alpha+phi_0);
end
