function event_apex = event(in1,in2,in3)
%EVENT
%    EVENT_APEX = EVENT(IN1,IN2,IN3)

%    This function was generated by the Symbolic Math Toolbox version 9.3.
%    09-Oct-2025 15:29:29

dy = in1(7,:);
event_apex = dy;
end
