function jump_apex = jump(in1,in2,in3)
%JUMP
%    JUMP_APEX = JUMP(IN1,IN2,IN3)

%    This function was generated by the Symbolic Math Toolbox version 9.3.
%    09-Oct-2025 15:29:30

alpha = in1(4,:);
dalpha = in1(9,:);
dl = in1(10,:);
dphi = in1(8,:);
dx = in1(6,:);
dy = in1(7,:);
l = in1(5,:);
phi = in1(3,:);
x = in1(1,:);
y = in1(2,:);
jump_apex = [x;y;phi;alpha;l;dx;dy;dphi;dalpha;dl];
end
