function W_S_dot = contactJacobianDerivative(in1,in2)
%contactJacobianDerivative
%    W_S_dot = contactJacobianDerivative(IN1,IN2)

%    This function was generated by the Symbolic Math Toolbox version 9.3.
%    07-Aug-2025 17:18:55

alpha = in1(3,:);
dalpha = in1(7,:);
dl = in1(8,:);
l = in1(4,:);
phi_0 = in2(11,:);
t2 = alpha+phi_0;
t3 = cos(t2);
t4 = sin(t2);
W_S_dot = reshape([0.0,0.0,dl.*t3-dalpha.*l.*t4,dalpha.*t3,0.0,0.0,dl.*t4+dalpha.*l.*t3,dalpha.*t4],[4,2]);
end
