function W_S = contactJacobian(in1,in2)
%contactJacobian
%    W_S = contactJacobian(IN1,IN2)

%    This function was generated by the Symbolic Math Toolbox version 9.3.
%    07-Aug-2025 17:18:55

alpha = in1(3,:);
l = in1(4,:);
phi_0 = in2(11,:);
r_f = in2(10,:);
t2 = alpha+phi_0;
t3 = cos(t2);
t4 = sin(t2);
W_S = reshape([1.0,0.0,r_f+l.*t3,t4,0.0,1.0,l.*t4,-t3],[4,2]);
end
