function f_S = dynamics(in1,in2,in3)
%DYNAMICS
%    f_S = DYNAMICS(IN1,IN2,IN3)

%    This function was generated by the Symbolic Math Toolbox version 24.2.
%    2025-10-30 15:46:59

alpha = in1(1,:);
d_f = in3(9,:);
d_l = in3(8,:);
dalpha = in1(3,:);
dl = in1(4,:);
g = in3(2,:);
k_h = in3(14,:);
k_l = in3(15,:);
l = in1(2,:);
l_0 = in3(3,:);
m = in3(1,:);
m_f = in3(5,:);
m_l = in3(4,:);
phi_0 = in3(11,:);
r_f = in3(10,:);
theta_f = in3(7,:);
theta_l = in3(6,:);
u_h = in2(1,:);
u_l = in2(2,:);
xi_h = in3(12,:);
xi_l = in3(13,:);
t2 = alpha+phi_0;
t3 = d_f.^2;
t4 = d_l.^2;
t5 = dalpha.^2;
t6 = l.^2;
t7 = l.^3;
t8 = l_0.^2;
t9 = m.^2;
t10 = m_f.^2;
t11 = m_l.^2;
t12 = r_f.^2;
t15 = -m_f;
t19 = d_f.*l_0.*m_f.*2.0;
t13 = cos(t2);
t14 = sin(t2);
t16 = m_f.*t3;
t17 = m_l.*t4;
t18 = m_f.*t8;
t21 = m+t15;
t20 = t14.^2;
t22 = t13.^2;
t23 = k_l.*t21;
t25 = t16+t17+t18+t19+theta_f+theta_l;
t24 = sqrt(t23);
t26 = k_h.*t25;
t27 = sqrt(t26);
et1 = -t17.*u_l-theta_f.*u_l-theta_l.*u_l+d_l.^3.*t5.*t11+k_l.*l.*t16+k_l.*l.*t17-k_l.*l_0.*t17+k_l.*l.*theta_f+k_l.*l.*theta_l-k_l.*l_0.*theta_f-k_l.*l_0.*theta_l+k_l.*m.*t7+k_l.*t7.*t15-m.*t6.*u_l-m.*t12.*u_l+m_f.*t6.*u_l-t5.*t7.*t9-t5.*t7.*t10+t3.*t15.*u_l-d_l.*k_l.*m_l.*t6.*2.0+d_l.*l.*m_l.*u_l.*2.0+k_l.*l.*m.*t12-k_l.*l_0.*m.*t6-k_l.*l_0.*m.*t12+k_l.*l_0.*m_f.*t6+d_l.*m_l.*t5.*t16+d_l.*m_l.*t5.*theta_f+d_l.*m_l.*t5.*theta_l+g.*m.*t13.*t16+g.*m.*t13.*t17+g.*m.*t13.*theta_f+g.*m.*t13.*theta_l+k_l.*l_0.*t3.*t15-l.*m.*t5.*t17+l.*m_f.*t5.*t17-l.*m.*t5.*theta_f-l.*m.*t5.*theta_l;
et2 = l.*m_f.*t5.*theta_f+l.*m_f.*t5.*theta_l+m.*m_f.*t5.*t7.*2.0-g.*t3.*t10.*t13+g.*t6.*t9.*t13+g.*t6.*t10.*t13+g.*t9.*t12.*t13+g.*t13.*t15.*t17+g.*t13.*t15.*theta_f+g.*t13.*t15.*theta_l+dl.*t16.*t24.*xi_l.*2.0+dl.*t17.*t24.*xi_l.*2.0+dl.*t24.*theta_f.*xi_l.*2.0+dl.*t24.*theta_l.*xi_l.*2.0+l.*t3.*t5.*t10-l.*t4.*t5.*t11.*2.0-l.*t5.*t9.*t12+m.*r_f.*t14.*u_h+r_f.*t14.*t15.*u_h+d_l.*k_l.*l.*l_0.*m_l.*2.0-alpha.*k_h.*m.*r_f.*t14+alpha.*k_h.*m_f.*r_f.*t14-d_f.*g.*r_f.*t10.*t20-d_f.*g.*r_f.*t10.*t22.*2.0+d_l.*m.*m_l.*t5.*t6.*3.0+d_l.*m.*m_l.*t5.*t12-d_l.*m_f.*m_l.*t5.*t6.*3.0-g.*m.*m_f.*t6.*t13.*2.0+g.*l.*r_f.*t9.*t20+g.*l.*r_f.*t10.*t20+g.*l.*r_f.*t9.*t22.*2.0+g.*l.*r_f.*t10.*t22.*2.0;
et3 = d_f.*m_f.*r_f.*t13.*u_l.*-2.0+d_l.*m_l.*r_f.*t13.*u_l.*2.0+l.*m.*m_f.*t5.*t12+g.*m.*t12.*t13.*t15+dl.*m.*t6.*t24.*xi_l.*2.0+dl.*m.*t12.*t24.*xi_l.*2.0-dl.*m_f.*t6.*t24.*xi_l.*2.0+k_l.*m.*r_f.*t6.*t13.*2.0-k_l.*m_f.*r_f.*t6.*t13.*2.0-d_f.*t5.*t10.*t12.*t20-l.*m.*r_f.*t13.*u_l.*2.0+l.*m.*t3.*t5.*t15+l.*m_f.*r_f.*t13.*u_l.*2.0+l.*t5.*t9.*t12.*t20+l.*t5.*t10.*t12.*t20-r_f.*t4.*t5.*t11.*t13.*2.0-r_f.*t5.*t6.*t9.*t13.*2.0-r_f.*t5.*t6.*t10.*t13.*2.0-l.*m.*m_f.*t5.*t12.*t20.*2.0-dalpha.*m.*r_f.*t14.*t27.*xi_h.*2.0+dalpha.*m_f.*r_f.*t14.*t27.*xi_h.*2.0+m.*m_f.*r_f.*t5.*t6.*t13.*4.0-d_l.*g.*l.*m.*m_l.*t13.*2.0+d_l.*g.*l.*m_f.*m_l.*t13.*2.0+d_f.*g.*m.*m_f.*r_f.*t20+d_f.*g.*m.*m_f.*r_f.*t22.*2.0;
et4 = -d_l.*g.*m.*m_l.*r_f.*t20-d_l.*g.*m.*m_l.*r_f.*t22.*2.0+d_l.*g.*m_f.*m_l.*r_f.*t20+d_l.*g.*m_f.*m_l.*r_f.*t22.*2.0-d_l.*dl.*l.*m_l.*t24.*xi_l.*4.0-dalpha.*dl.*l.*r_f.*t9.*t14.*2.0-dalpha.*dl.*l.*r_f.*t10.*t14.*2.0+d_f.*k_l.*l.*m_f.*r_f.*t13.*2.0-d_l.*k_l.*l.*m_l.*r_f.*t13.*2.0-d_f.*k_l.*l_0.*m_f.*r_f.*t13.*2.0+d_l.*k_l.*l_0.*m_l.*r_f.*t13.*2.0-g.*l.*m.*m_f.*r_f.*t20.*2.0-g.*l.*m.*m_f.*r_f.*t22.*4.0-k_l.*l.*l_0.*m.*r_f.*t13.*2.0+k_l.*l.*l_0.*m_f.*r_f.*t13.*2.0-dalpha.*dl.*t9.*t12.*t13.*t14.*2.0-dalpha.*dl.*t10.*t12.*t13.*t14.*2.0+d_f.*m.*m_f.*t5.*t12.*t20-d_l.*m.*m_l.*t5.*t12.*t20+d_l.*m_f.*m_l.*t5.*t12.*t20+d_f.*l.*r_f.*t5.*t10.*t13.*2.0+d_l.*dalpha.*dl.*m.*m_l.*r_f.*t14.*2.0-d_l.*dalpha.*dl.*m_f.*m_l.*r_f.*t14.*2.0;
et5 = dalpha.*dl.*l.*m.*m_f.*r_f.*t14.*4.0+d_f.*d_l.*m_f.*m_l.*r_f.*t5.*t13.*2.0+dalpha.*dl.*m.*m_f.*t12.*t13.*t14.*4.0-d_f.*l.*m.*m_f.*r_f.*t5.*t13.*2.0+d_l.*l.*m.*m_l.*r_f.*t5.*t13.*4.0-d_l.*l.*m_f.*m_l.*r_f.*t5.*t13.*4.0+d_f.*dl.*m_f.*r_f.*t13.*t24.*xi_l.*4.0-d_l.*dl.*m_l.*r_f.*t13.*t24.*xi_l.*4.0+dl.*l.*m.*r_f.*t13.*t24.*xi_l.*4.0-dl.*l.*m_f.*r_f.*t13.*t24.*xi_l.*4.0;
mt1 = [dalpha;dl;(u_h-alpha.*k_h-dalpha.*t27.*xi_h.*2.0-r_f.*t14.*u_l-dalpha.*dl.*l.*m.*2.0+dalpha.*dl.*l.*m_f.*2.0+d_f.*g.*m_f.*t14-d_l.*g.*m_l.*t14+g.*l.*m.*t14+g.*l.*t14.*t15+k_l.*l.*r_f.*t14-k_l.*l_0.*r_f.*t14+d_l.*dalpha.*dl.*m_l.*2.0-dalpha.*dl.*m.*r_f.*t13.*2.0+dalpha.*dl.*m_f.*r_f.*t13.*2.0+d_f.*m_f.*r_f.*t5.*t14+g.*m.*r_f.*t13.*t14+g.*r_f.*t13.*t14.*t15+dl.*r_f.*t14.*t24.*xi_l.*2.0)./(t16+t17+theta_f+theta_l+m.*t6+m.*t12+t6.*t15-d_l.*l.*m_l.*2.0-m.*t12.*t20+m_f.*t12.*t20+d_f.*m_f.*r_f.*t13.*2.0-d_l.*m_l.*r_f.*t13.*2.0+l.*m.*r_f.*t13.*2.0-l.*m_f.*r_f.*t13.*2.0)];
mt2 = [-(et1+et2+et3+et4+et5)./(m.*t16+m.*t17+m.*theta_f+m.*theta_l-t3.*t10+t6.*t9+t6.*t10+t9.*t12+t15.*t17+t15.*theta_f+t15.*theta_l-m.*m_f.*t6.*2.0+m.*t12.*t15-t9.*t12.*t20-t10.*t12.*t20-d_l.*l.*m.*m_l.*2.0+d_l.*l.*m_f.*m_l.*2.0-d_f.*r_f.*t10.*t13.*2.0+m.*m_f.*t12.*t20.*2.0+l.*r_f.*t9.*t13.*2.0+l.*r_f.*t10.*t13.*2.0+d_f.*m.*m_f.*r_f.*t13.*2.0-d_l.*m.*m_l.*r_f.*t13.*2.0+d_l.*m_f.*m_l.*r_f.*t13.*2.0-l.*m.*m_f.*r_f.*t13.*4.0)];
f_S = [mt1;mt2];
end
