function E = energyLevel(in1,in2,in3)
%energyLevel
%    E = energyLevel(IN1,IN2,IN3)

%    This function was generated by the Symbolic Math Toolbox version 24.2.
%    2025-10-30 15:46:59

alpha = in1(1,:);
d_f = in3(9,:);
d_l = in3(8,:);
dalpha = in1(3,:);
dl = in1(4,:);
g = in3(2,:);
k_h = in3(14,:);
k_l = in3(15,:);
l = in1(2,:);
l_0 = in3(3,:);
m = in3(1,:);
m_f = in3(5,:);
m_l = in3(4,:);
phi_0 = in3(11,:);
r_f = in3(10,:);
theta_f = in3(7,:);
theta_l = in3(6,:);
t2 = alpha+phi_0;
t3 = dalpha.^2;
t6 = -l;
t7 = -m;
t4 = cos(t2);
t5 = sin(t2);
t13 = d_f+t6;
t14 = m_f+m_l+t7;
t8 = d_l.*t4;
t9 = dl.*t4;
t10 = l.*t4;
t11 = dl.*t5;
t12 = l.*t5;
t17 = t4.*t13;
t15 = r_f+t10;
t19 = t15+t17;
E = (m_f.*(t3.*(t12+t5.*t13).^2+t3.*t19.^2))./2.0+(t3.*theta_f)./2.0+(t3.*theta_l)./2.0-(t14.*((t11+dalpha.*t15).^2+(t9+dalpha.*t5.*t6).^2))./2.0+(alpha.^2.*k_h)./2.0+(m_l.*((t11-dalpha.*(t8-t15)).^2+(t9+dalpha.*(d_l.*t5+t5.*t6)).^2))./2.0+(k_l.*(l-l_0).^2)./2.0+g.*m_f.*t19-g.*t14.*t15-g.*m_l.*(t8-t15);
end
