function out1 = forces(in1,in2,in3)
%FORCES
%    OUT1 = FORCES(IN1,IN2,IN3)

%    This function was generated by the Symbolic Math Toolbox version 24.2.
%    2025-10-30 15:46:59

alpha = in1(1,:);
d_f = in3(9,:);
d_l = in3(8,:);
dalpha = in1(3,:);
dl = in1(4,:);
g = in3(2,:);
k_h = in3(14,:);
k_l = in3(15,:);
l = in1(2,:);
l_0 = in3(3,:);
m = in3(1,:);
m_f = in3(5,:);
m_l = in3(4,:);
phi_0 = in3(11,:);
r_f = in3(10,:);
theta_f = in3(7,:);
theta_l = in3(6,:);
u_h = in2(1,:);
u_l = in2(2,:);
xi_h = in3(12,:);
xi_l = in3(13,:);
t2 = d_l.*m_l;
t3 = alpha+phi_0;
t4 = l.*m;
t5 = l.*m_f;
t6 = dalpha.^2;
t9 = -m_f;
t7 = cos(t3);
t8 = sin(t3);
t10 = m+t9;
out1 = [u_h-alpha.*k_h-dalpha.*xi_h.*sqrt(k_h.*(theta_f+theta_l+d_l.*t2+m_f.*(d_f+l_0).^2)).*2.0-g.*t8.*(t2-t4+t5+d_f.*t9)+dalpha.*dl.*t2.*2.0-dalpha.*dl.*t4.*2.0+dalpha.*dl.*t5.*2.0-r_f.*t2.*t6.*t8+r_f.*t4.*t6.*t8-r_f.*t5.*t6.*t8-dalpha.*dl.*m.*r_f.*t7.*2.0+dalpha.*dl.*m_f.*r_f.*t7.*2.0+d_f.*m_f.*r_f.*t6.*t8;u_l-k_l.*(l-l_0)-t6.*(t2-t4+t5)-g.*t7.*t10-dl.*xi_l.*sqrt(k_l.*t10).*2.0];
end
