function M = massMatrix(in1,in2)
%massMatrix
%    M = massMatrix(IN1,IN2)

%    This function was generated by the Symbolic Math Toolbox version 24.2.
%    2025-10-30 15:46:59

alpha = in1(1,:);
d_f = in2(9,:);
d_l = in2(8,:);
l = in1(2,:);
m = in2(1,:);
m_f = in2(5,:);
m_l = in2(4,:);
phi_0 = in2(11,:);
r_f = in2(10,:);
theta_f = in2(7,:);
theta_l = in2(6,:);
t2 = alpha+phi_0;
t3 = l.^2;
t6 = -m_f;
t4 = cos(t2);
t5 = sin(t2);
t7 = m+t6;
t8 = r_f.*t5.*t7;
M = reshape([theta_f+theta_l+m.*t3+t3.*t6+d_f.^2.*m_f+d_l.^2.*m_l+m.*r_f.^2-d_l.*l.*m_l.*2.0+d_f.*m_f.*r_f.*t4.*2.0-d_l.*m_l.*r_f.*t4.*2.0+l.*m.*r_f.*t4.*2.0-l.*m_f.*r_f.*t4.*2.0,t8,t8,t7],[2,2]);
end
