function posMechWork = posMechWork(in1,in2)
%posMechWork
%    posMechWork = posMechWork(IN1,IN2)

%    This function was generated by the Symbolic Math Toolbox version 24.2.
%    2025-10-30 15:46:59

dalpha = in1(3,:);
dl = in1(4,:);
u_h = in2(1,:);
u_l = in2(2,:);
posMechWork = dalpha.*u_h.*(9.0./2.0e+1)+dl.*u_l.*(9.0./2.0e+1)+sqrt(((dalpha.*u_h)./2.0+(dl.*u_l)./2.0).^2+9.0./1.0e+2).*(1.1e+1./1.0e+1);
end
