function event_apex = event(in1,in2,in3)
%EVENT
%    EVENT_APEX = EVENT(IN1,IN2,IN3)

%    This function was generated by the Symbolic Math Toolbox version 9.3.
%    04-Aug-2025 16:50:45

dy = in1(6,:);
event_apex = dy;
end
