function jump_apex = jump(in1,in2,in3)
%JUMP
%    JUMP_APEX = JUMP(IN1,IN2,IN3)

%    This function was generated by the Symbolic Math Toolbox version 9.3.
%    04-Aug-2025 16:50:45

alpha = in1(3,:);
dalpha = in1(7,:);
dl = in1(8,:);
dx = in1(5,:);
dy = in1(6,:);
l = in1(4,:);
x = in1(1,:);
y = in1(2,:);
jump_apex = [x;y;alpha;l;dx;dy;dalpha;dl];
end
