function dJ_StanceConstraint_m = dJ_StanceConstraint_m(in1,in2)
%dJ_StanceConstraint_m
%    dJ_StanceConstraint_m = dJ_StanceConstraint_m(IN1,IN2)

%    This function was generated by the Symbolic Math Toolbox version 24.2.
%    2026-04-02 20:01:42

dJ_StanceConstraint_m = reshape([0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0],[2,5]);
end
