function dJ_StanceConstraint_f = dJ_StanceConstraint_f(in1,in2)
%dJ_StanceConstraint_f
%    dJ_StanceConstraint_f = dJ_StanceConstraint_f(IN1,IN2)

%    This function was generated by the Symbolic Math Toolbox version 24.2.
%    2026-04-02 20:01:42

dJ_StanceConstraint_f = reshape([0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0],[2,7]);
end
