function dJ_SwingConstraint_m = dJ_SwingConstraint_m(in1,in2)
%dJ_SwingConstraint_m
%    dJ_SwingConstraint_m = dJ_SwingConstraint_m(IN1,IN2)

%    This function was generated by the Symbolic Math Toolbox version 24.2.
%    2026-02-18 12:02:49

alpha_l = in1(2,:);
alpha_r = in1(3,:);
beta_l = in1(4,:);
beta_r = in1(5,:);
dalpha_l = in1(7,:);
dalpha_r = in1(8,:);
dbeta_l = in1(9,:);
dbeta_r = in1(10,:);
dphi = in1(6,:);
l = in2(3,:);
l_2 = in2(10,:);
phi = in1(1,:);
t2 = alpha_l+phi;
t3 = alpha_r+phi;
t10 = -l_2;
t4 = beta_l+t2;
t5 = beta_r+t3;
t6 = cos(t2);
t7 = cos(t3);
t8 = sin(t2);
t9 = sin(t3);
t19 = l+t10;
t11 = sin(t4);
t12 = sin(t5);
t13 = cos(t4);
t14 = cos(t5);
t15 = l_2.*t6;
t16 = l_2.*t7;
t17 = l_2.*t8;
t18 = l_2.*t9;
t20 = t13.*t19;
t21 = t14.*t19;
t22 = t11.*t19;
t23 = t12.*t19;
t24 = dbeta_l.*t20;
t25 = dbeta_r.*t21;
t26 = dbeta_l.*t22;
t27 = dbeta_r.*t23;
t30 = t15+t20;
t31 = t16+t21;
t32 = t17+t22;
t33 = t18+t23;
t28 = -t24;
t29 = -t27;
t34 = dalpha_l.*t30;
t35 = dalpha_r.*t31;
t36 = dalpha_l.*t32;
t37 = dalpha_r.*t33;
t38 = -t34;
t39 = -t37;
dJ_SwingConstraint_m = reshape([t26+t29+t36+t39+dphi.*(-t23+t32+t9.*t10),t25+t28+t35+t38-dphi.*(-t21+t30+t7.*t10),t26+t36+dphi.*t32,t28+t38-dphi.*t30,t29+t39-dphi.*t33,t25+t35+dphi.*t31,t26+dalpha_l.*t22+dphi.*t22,t28-dalpha_l.*t20-dphi.*t20,t29-dalpha_r.*t23-dphi.*t23,t25+dalpha_r.*t21+dphi.*t21],[2,5]);
end
