function J_Hip_m = J_Hip_m(in1,in2)
%J_Hip_m
%    J_Hip_m = J_Hip_m(IN1,IN2)

%    This function was generated by the Symbolic Math Toolbox version 24.2.
%    2026-02-18 12:02:49

alpha_l = in1(2,:);
beta_l = in1(4,:);
l = in2(3,:);
l_2 = in2(10,:);
phi = in1(1,:);
t2 = alpha_l+phi;
t6 = -l_2;
t3 = beta_l+t2;
t4 = cos(t2);
t5 = sin(t2);
t11 = l+t6;
t7 = sin(t3);
t8 = cos(t3);
t12 = t4.*t6;
t13 = t5.*t6;
t14 = t8.*t11;
t15 = t7.*t11;
t16 = -t14;
t17 = -t15;
t18 = t12+t16;
t19 = t13+t17;
J_Hip_m = reshape([t18,t19,t18,t19,0.0,0.0,t16,t17,0.0,0.0],[2,5]);
end
