function J_SwingConstraint_f = J_SwingConstraint_f(in1,in2)
%J_SwingConstraint_f
%    J_SwingConstraint_f = J_SwingConstraint_f(IN1,IN2)

%    This function was generated by the Symbolic Math Toolbox version 24.2.
%    2026-04-02 20:01:43

alpha_l = in1(4,:);
alpha_r = in1(5,:);
beta_l = in1(6,:);
beta_r = in1(7,:);
l = in2(3,:);
l_2 = in2(10,:);
phi = in1(3,:);
t2 = alpha_l+phi;
t3 = alpha_r+phi;
t10 = -l_2;
t4 = beta_l+t2;
t5 = beta_r+t3;
t6 = cos(t2);
t7 = cos(t3);
t8 = sin(t2);
t9 = sin(t3);
t19 = l+t10;
t11 = sin(t4);
t12 = sin(t5);
t13 = cos(t4);
t14 = cos(t5);
t16 = l_2.*t7;
t18 = l_2.*t9;
t20 = t6.*t10;
t21 = t8.*t10;
t22 = t13.*t19;
t23 = t14.*t19;
t24 = t11.*t19;
t25 = t12.*t19;
t26 = -t22;
t27 = -t24;
J_SwingConstraint_f = reshape([1.0,0.0,0.0,1.0,t16+t20+t23+t26,t18+t21+t25+t27,t20+t26,t21+t27,t16+t23,t18+t25,t26,t27,t23,t25],[2,7]);
end
