function pos_StanceFoot_f = pos_StanceFoot_f(in1,in2)
%pos_StanceFoot_f
%    pos_StanceFoot_f = pos_StanceFoot_f(IN1,IN2)

%    This function was generated by the Symbolic Math Toolbox version 24.2.
%    2026-02-18 12:02:48

x = in1(1,:);
y = in1(2,:);
pos_StanceFoot_f = [x;y];
end
