function tau_Spring_m = tau_Spring_m(in1,in2)
%tau_Spring_m
%    tau_Spring_m = tau_Spring_m(IN1,IN2)

%    This function was generated by the Symbolic Math Toolbox version 24.2.
%    2026-02-18 12:02:50

alpha0 = in2(14,:);
alpha_l = in1(2,:);
alpha_r = in1(3,:);
beta0 = in2(15,:);
beta_l = in1(4,:);
beta_r = in1(5,:);
dalpha_l = in1(7,:);
dalpha_r = in1(8,:);
dbeta_l = in1(9,:);
dbeta_r = in1(10,:);
k_h = in2(18,:);
k_k = in2(19,:);
tau_Spring_m = [0.0;dalpha_l.*(-3.3e+1./2.0)+k_h.*(alpha0-alpha_l);dalpha_r.*(-3.3e+1./2.0)+k_h.*(alpha0-alpha_r);dbeta_l.*(-1.37e+2./2.5e+1)+k_k.*(beta0-beta_l);dbeta_r.*(-1.37e+2./2.5e+1)+k_k.*(beta0-beta_r)];
end
