function E = energyLevel(in1,u,in3)
%energyLevel
%    E = energyLevel(IN1,U,IN3)

%    This function was generated by the Symbolic Math Toolbox version 9.3.
%    23-May-2025 16:10:58

d_l = in3(6,:);
dl = in1(2,:);
g = in3(2,:);
k_l = in3(10,:);
l = in1(1,:);
l_0 = in3(3,:);
m = in3(1,:);
m_f = in3(5,:);
m_l = in3(4,:);
r_f = in3(8,:);
t2 = l+r_f;
E = dl.^2.*(m./2.0-m_f./2.0)-g.*(m_l.*(d_l-t2)+t2.*(-m+m_f+m_l))+(k_l.*(l-l_0).^2)./2.0;
end
