function out1 = forces(in1,u,in3)
%FORCES
%    OUT1 = FORCES(IN1,U,IN3)

%    This function was generated by the Symbolic Math Toolbox version 9.3.
%    23-May-2025 16:10:58

dl = in1(2,:);
g = in3(2,:);
k_l = in3(10,:);
l = in1(1,:);
l_0 = in3(3,:);
m = in3(1,:);
m_f = in3(5,:);
xi_l = in3(9,:);
t2 = -m_f;
t3 = m+t2;
out1 = u-g.*t3-k_l.*(l-l_0)-dl.*xi_l.*sqrt(k_l.*t3).*2.0;
end
