function [A_lin,B_lin,D_lin] = get_linearDynamics(in1)
%get_linearDynamics
%    [A_lin,B_lin,D_lin] = get_linearDynamics(IN1)

%    This function was generated by the Symbolic Math Toolbox version 9.3.
%    23-May-2025 16:10:58

g = in1(2,:);
k_l = in1(10,:);
l_0 = in1(3,:);
m = in1(1,:);
m_f = in1(5,:);
xi_l = in1(9,:);
t2 = -m_f;
t3 = m+t2;
t4 = 1.0./t3;
A_lin = reshape([0.0,-k_l.*t4,1.0,t4.*xi_l.*sqrt(k_l.*t3).*-2.0],[2,2]);
if nargout > 1
    B_lin = [0.0;t4];
end
if nargout > 2
    D_lin = [0.0;t4.*(-g.*m+g.*m_f+k_l.*l_0)];
end
end
