function M = massMatrix(in1,in2)
%massMatrix
%    M = massMatrix(IN1,IN2)

%    This function was generated by the Symbolic Math Toolbox version 9.3.
%    23-May-2025 16:10:58

m = in2(1,:);
m_f = in2(5,:);
M = m-m_f;
end
