function pos_SwingFoot_f = pos_SwingFoot_f(in1,in2)
%pos_SwingFoot_f
%    pos_SwingFoot_f = pos_SwingFoot_f(IN1,IN2)

%    This function was generated by the Symbolic Math Toolbox version 24.2.
%    2026-04-03 18:37:57

alpha_l = in1(4,:);
alpha_r = in1(5,:);
beta_l = in1(6,:);
beta_r = in1(7,:);
l = in2(3,:);
l_2 = in2(10,:);
phi = in1(3,:);
x = in1(1,:);
y = in1(2,:);
t2 = alpha_l+phi;
t3 = alpha_r+phi;
t6 = -l_2;
t4 = beta_l+t2;
t5 = beta_r+t3;
t7 = l+t6;
pos_SwingFoot_f = [x+l_2.*sin(t3)+t6.*sin(t2)-t7.*sin(t4)+t7.*sin(t5);y+l_2.*cos(t2)+t6.*cos(t3)+t7.*cos(t4)-t7.*cos(t5)];
end
