function CoGs_m = CoGPositions_m(in1,in2)
%CoGPositions_m
%    CoGs_m = CoGPositions_m(IN1,IN2)

%    This function was generated by the Symbolic Math Toolbox version 24.2.
%    2026-02-05 16:00:36

alpha_l = in1(2,:);
alpha_r = in1(3,:);
beta_l = in1(4,:);
beta_r = in1(5,:);
d_1 = in2(11,:);
d_2 = in2(12,:);
d_3 = in2(13,:);
l = in2(3,:);
l_2 = in2(10,:);
phi = in1(1,:);
t2 = alpha_l+phi;
t3 = alpha_r+phi;
t10 = -l;
t11 = -l_2;
t4 = beta_l+t2;
t5 = beta_r+t3;
t6 = cos(t2);
t7 = cos(t3);
t8 = sin(t2);
t9 = sin(t3);
t16 = d_2+t11;
t17 = l+t11;
t18 = d_3+l_2+t10;
t12 = sin(t4);
t13 = cos(t4);
t14 = l_2.*t6;
t19 = t8.*t11;
t20 = t13.*t17;
t21 = t12.*t17;
t22 = -t21;
CoGs_m = reshape([t19+t22-d_1.*sin(phi),t14+t20+d_1.*cos(phi),phi,t22+t8.*t16,t20-t6.*t16,t2,t12.*t18,-t13.*t18,t4,t19+t22+d_2.*t9,t14+t20-d_2.*t7,t3,t19+t22+l_2.*t9+d_3.*sin(t5),t14+t20+t7.*t11-d_3.*cos(t5),t5],[3,5]);
end
