function J_StanceConstraint_f = J_StanceConstraint_f(in1,in2)
%J_StanceConstraint_f
%    J_StanceConstraint_f = J_StanceConstraint_f(IN1,IN2)

%    This function was generated by the Symbolic Math Toolbox version 24.2.
%    2026-04-03 18:36:48

J_StanceConstraint_f = reshape([1.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0],[2,7]);
end
