function J_StanceConstraint_m = J_StanceConstraint_m(in1,in2)
%J_StanceConstraint_m
%    J_StanceConstraint_m = J_StanceConstraint_m(IN1,IN2)

%    This function was generated by the Symbolic Math Toolbox version 24.2.
%    2026-04-03 18:36:48

J_StanceConstraint_m = reshape([0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0],[2,5]);
end
