function links_m = LinkPositions_m(in1,in2)
%LinkPositions_m
%    LINKS_M = LinkPositions_m(IN1,IN2)

%    This function was generated by the Symbolic Math Toolbox version 24.2.
%    2026-04-03 18:36:49

alpha_l = in1(2,:);
alpha_r = in1(3,:);
beta_l = in1(4,:);
beta_r = in1(5,:);
l = in2(3,:);
l_1 = in2(9,:);
l_2 = in2(10,:);
phi = in1(1,:);
t2 = alpha_l+phi;
t3 = alpha_r+phi;
t10 = -l_2;
t4 = beta_l+t2;
t5 = beta_r+t3;
t6 = cos(t2);
t7 = cos(t3);
t8 = sin(t2);
t9 = sin(t3);
t17 = l+t10;
t11 = sin(t4);
t12 = cos(t4);
t13 = l_2.*t6;
t16 = l_2.*t9;
t18 = t7.*t10;
t19 = t8.*t10;
t20 = t12.*t17;
t21 = t11.*t17;
t22 = -t21;
links_m = reshape([0.0,0.0,t22,t20,t19+t22,t13+t20,t19+t22-l_1.*sin(phi),t13+t20+l_1.*cos(phi),t16+t19+t22,t13+t18+t20,t16+t19+t22+t17.*sin(t5),t13+t18+t20-t17.*cos(t5)],[2,6]);
end
