function pos_StanceFoot_m = pos_StanceFoot_m(in1,in2)
%pos_StanceFoot_m
%    pos_StanceFoot_m = pos_StanceFoot_m(IN1,IN2)

%    This function was generated by the Symbolic Math Toolbox version 24.2.
%    2026-02-05 16:00:35

pos_StanceFoot_m = [0.0;0.0];
end
