function posMechWork = posMechWork(in1,in2)
%posMechWork
%    posMechWork = posMechWork(IN1,IN2)

%    This function was generated by the Symbolic Math Toolbox version 24.2.
%    2026-04-03 18:36:47

dalpha_l = in1(7,:);
dalpha_r = in1(8,:);
dbeta_l = in1(9,:);
dbeta_r = in1(10,:);
u_hl = in2(1,:);
u_hr = in2(2,:);
u_kl = in2(3,:);
u_kr = in2(4,:);
posMechWork = dalpha_l.*u_hl.*(9.0./2.0e+1)+dalpha_r.*u_hr.*(9.0./2.0e+1)+dbeta_l.*u_kl.*(9.0./2.0e+1)+dbeta_r.*u_kr.*(9.0./2.0e+1)+sqrt(((dalpha_l.*u_hl)./2.0+(dalpha_r.*u_hr)./2.0+(dbeta_l.*u_kl)./2.0+(dbeta_r.*u_kr)./2.0).^2+9.0./1.0e+2).*(1.1e+1./1.0e+1);
end
