function event_td = event(in1,in2,in3)
%EVENT
%    EVENT_TD = EVENT(IN1,IN2,IN3)

%    This function was generated by the Symbolic Math Toolbox version 24.2.
%    2026-02-09 17:45:02

alpha_l = in1(4,:);
alpha_r = in1(5,:);
beta_l = in1(6,:);
beta_r = in1(7,:);
l = in3(3,:);
l_2 = in3(10,:);
phi = in1(3,:);
y = in1(2,:);
t2 = -l_2;
t3 = l+t2;
event_td = y+l_2.*cos(alpha_l+phi)+t2.*cos(alpha_r+phi)+t3.*cos(alpha_l+beta_l+phi)-t3.*cos(alpha_r+beta_r+phi);
end
