function E = energyLevel(in1,in2,in3)
%energyLevel
%    E = energyLevel(IN1,IN2,IN3)

%    This function was generated by the Symbolic Math Toolbox version 9.3.
%    09-Oct-2025 15:29:26

alpha = in1(4,:);
d_f = in3(10,:);
d_l = in3(9,:);
dalpha = in1(9,:);
dl = in1(10,:);
dphi = in1(8,:);
dx = in1(6,:);
dy = in1(7,:);
g = in3(2,:);
k_h = in3(14,:);
k_l = in3(15,:);
l = in1(5,:);
l_0 = in3(3,:);
m = in3(1,:);
m_f = in3(5,:);
m_l = in3(4,:);
phi = in1(3,:);
theta_f = in3(8,:);
theta_l = in3(7,:);
theta_t = in3(6,:);
y = in1(2,:);
t2 = dalpha+dphi;
t3 = alpha+phi;
t6 = -l;
t7 = -m;
t4 = cos(t3);
t5 = sin(t3);
t8 = t2.^2;
t9 = d_f+t6;
t10 = m_f+m_l+t7;
E = (t8.*theta_f)./2.0+(t8.*theta_l)./2.0+(alpha.^2.*k_h)./2.0+(dphi.^2.*theta_t)./2.0-(t10.*(dx.^2+dy.^2))./2.0+(k_l.*(l-l_0).^2)./2.0+(m_l.*((dx+d_l.*dalpha.*t4+d_l.*dphi.*t4).^2+(dy+d_l.*dalpha.*t5+d_l.*dphi.*t5).^2))./2.0+(m_f.*((-dy+dl.*t4+dalpha.*t5.*t9+dphi.*t5.*t9).^2+(dx+dl.*t5-dalpha.*t4.*t9-dphi.*t4.*t9).^2))./2.0+g.*m_l.*(y-d_l.*t4)+g.*m_f.*(y+t4.*t9)-g.*t10.*y;
end
