function out1 = forces(in1,in2,in3)
%FORCES
%    OUT1 = FORCES(IN1,IN2,IN3)

%    This function was generated by the Symbolic Math Toolbox version 9.3.
%    09-Oct-2025 15:29:25

alpha = in1(4,:);
d_f = in3(10,:);
d_l = in3(9,:);
dalpha = in1(9,:);
dl = in1(10,:);
dphi = in1(8,:);
g = in3(2,:);
k_h = in3(14,:);
k_l = in3(15,:);
l = in1(5,:);
l_0 = in3(3,:);
m = in3(1,:);
m_f = in3(5,:);
m_l = in3(4,:);
phi = in1(3,:);
theta_f = in3(8,:);
theta_l = in3(7,:);
u_h = in2(1,:);
u_l = in2(2,:);
xi_h = in3(12,:);
xi_l = in3(13,:);
t2 = dalpha+dphi;
t3 = d_f.*m_f;
t4 = d_l.*m_l;
t5 = alpha+phi;
t6 = l.*m_f;
t9 = -l;
t7 = cos(t5);
t8 = sin(t5);
t10 = -t3;
t11 = d_f+t9;
t12 = t4+t6+t10;
t13 = dl.*m_f.*t2.*t11.*2.0;
t14 = g.*t8.*t12;
t15 = -t14;
out1 = [t2.*(dl.*m_f.*t7.*-2.0+dalpha.*t4.*t8+dalpha.*t6.*t8+dalpha.*t8.*t10+dphi.*t4.*t8+dphi.*t6.*t8+dphi.*t8.*t10);-g.*m-t2.*(dl.*m_f.*t8.*2.0+dalpha.*t4.*t7+dalpha.*t6.*t7+dalpha.*t7.*t10+dphi.*t4.*t7+dphi.*t6.*t7+dphi.*t7.*t10);t13+t15;t13+t15+u_h-alpha.*k_h-dalpha.*xi_h.*sqrt(k_h.*(theta_f+theta_l+d_l.*t4+m_f.*(d_f+l_0).^2)).*2.0;u_l-k_l.*(l-l_0)-m_f.*t2.^2.*t11+g.*m_f.*t7-dl.*xi_l.*sqrt(k_l.*(m-m_f)).*2.0];
end
