function event_td = event(in1,u,in3)
%EVENT
%    EVENT_TD = EVENT(IN1,U,IN3)

%    This function was generated by the Symbolic Math Toolbox version 9.3.
%    19-May-2025 16:56:38

l = in1(2,:);
r_f = in3(8,:);
y = in1(1,:);
event_td = -l-r_f+y;
end
