function jump_td = jump(in1,u,in3)
%JUMP
%    JUMP_TD = JUMP(IN1,U,IN3)

%    This function was generated by the Symbolic Math Toolbox version 9.3.
%    19-May-2025 16:56:38

dy = in1(3,:);
l = in1(2,:);
jump_td = [l;dy];
end
