function event_nadir = event(in1,in2,in3)
%EVENT
%    EVENT_NADIR = EVENT(IN1,IN2,IN3)

%    This function was generated by the Symbolic Math Toolbox version 9.3.
%    09-Oct-2025 15:26:37

dl = in1(10,:);
event_nadir = -dl;
end
