function jump_lo = jump(in1,u,in3)
%JUMP
%    JUMP_LO = JUMP(IN1,U,IN3)

%    This function was generated by the Symbolic Math Toolbox version 9.3.
%    23-May-2025 16:10:58

dl = in1(2,:);
l = in1(1,:);
r_f = in3(8,:);
jump_lo = [l+r_f;l;dl;dl];
end
