function W_S_dot = contactJacobianDerivative(in1,in2)
%contactJacobianDerivative
%    W_S_dot = contactJacobianDerivative(IN1,IN2)

%    This function was generated by the Symbolic Math Toolbox version 9.3.
%    19-May-2025 16:56:37

W_S_dot = [0.0;0.0];
end
