function W_S = contactJacobian(in1,in2)
%contactJacobian
%    W_S = contactJacobian(IN1,IN2)

%    This function was generated by the Symbolic Math Toolbox version 9.3.
%    19-May-2025 16:56:37

W_S = [1.0;-1.0];
end
