function f = dynamics(in1,u,in3)
%DYNAMICS
%    F = DYNAMICS(IN1,U,IN3)

%    This function was generated by the Symbolic Math Toolbox version 9.3.
%    19-May-2025 16:56:36

dl = in1(4,:);
dy = in1(3,:);
g = in3(2,:);
k_l = in3(10,:);
l = in1(2,:);
l_0 = in3(3,:);
m = in3(1,:);
m_f = in3(5,:);
xi_l = in3(9,:);
t2 = k_l.*l;
t3 = k_l.*l_0;
t4 = -m_f;
t6 = m+t4;
t7 = k_l.*t6;
t8 = 1.0./t6;
t9 = sqrt(t7);
t10 = dl.*t9.*xi_l.*2.0;
f = [dy;dl;-t8.*(t2-t3+t10-u+g.*m+g.*t4);-(m.*t8.*(t2-t3+t10-u))./m_f];
end
