function E = energyLevel(in1,u,in3)
%energyLevel
%    E = energyLevel(IN1,U,IN3)

%    This function was generated by the Symbolic Math Toolbox version 9.3.
%    19-May-2025 16:56:37

d_f = in3(7,:);
d_l = in3(6,:);
dl = in1(4,:);
dy = in1(3,:);
g = in3(2,:);
k_l = in3(10,:);
l = in1(2,:);
l_0 = in3(3,:);
m = in3(1,:);
m_f = in3(5,:);
m_l = in3(4,:);
y = in1(1,:);
t2 = m_f./2.0;
E = dy.^2.*(m./2.0-t2)-g.*(m_l.*(d_l-y)+y.*(-m+m_f+m_l))+t2.*(dl-dy).^2+(k_l.*(l-l_0).^2)./2.0+g.*m_f.*(d_f-l+y);
end
