function out1 = forces(in1,u,in3)
%FORCES
%    OUT1 = FORCES(IN1,U,IN3)

%    This function was generated by the Symbolic Math Toolbox version 9.3.
%    19-May-2025 16:56:37

dl = in1(4,:);
g = in3(2,:);
k_l = in3(10,:);
l = in1(2,:);
l_0 = in3(3,:);
m = in3(1,:);
m_f = in3(5,:);
xi_l = in3(9,:);
t2 = -l_0;
t3 = -m_f;
t4 = l+t2;
t5 = m+t3;
t6 = k_l.*t4;
t7 = k_l.*t5;
t8 = -t6;
t9 = sqrt(t7);
t10 = dl.*t9.*xi_l.*2.0;
t11 = -t10;
out1 = [t8+t11-g.*m;t8+t11+u+g.*m_f];
end
