function [A_lin,B_lin,D_lin] = get_linearDynamics(in1)
%get_linearDynamics
%    [A_lin,B_lin,D_lin] = get_linearDynamics(IN1)

%    This function was generated by the Symbolic Math Toolbox version 9.3.
%    19-May-2025 16:56:37

g = in1(2,:);
k_l = in1(10,:);
l_0 = in1(3,:);
m = in1(1,:);
m_f = in1(5,:);
xi_l = in1(9,:);
t2 = -m_f;
t3 = 1.0./m_f;
t4 = m+t2;
t5 = k_l.*t4;
t6 = 1.0./t4;
t7 = sqrt(t5);
A_lin = reshape([0.0,0.0,0.0,0.0,0.0,0.0,-k_l.*t6,-k_l.*m.*t3.*t6,1.0,0.0,0.0,0.0,0.0,1.0,t6.*t7.*xi_l.*-2.0,m.*t3.*t6.*t7.*xi_l.*-2.0],[4,4]);
if nargout > 1
    B_lin = [0.0;0.0;t6;m.*t3.*t6];
end
if nargout > 2
    D_lin = [0.0;0.0;t6.*(-g.*m+g.*m_f+k_l.*l_0);k_l.*l_0.*m.*t3.*t6];
end
end
