function [A_min,B_min,D_min,T_coord] = get_reducedDynamics(in1)
%get_reducedDynamics
%    [A_min,B_min,D_min,T_coord] = get_reducedDynamics(IN1)

%    This function was generated by the Symbolic Math Toolbox version 9.3.
%    19-May-2025 16:56:37

k_l = in1(10,:);
l_0 = in1(3,:);
m = in1(1,:);
m_f = in1(5,:);
xi_l = in1(9,:);
t2 = 1.0./m;
t3 = -m_f;
t4 = 1.0./m_f;
t5 = m+t3;
t7 = t2.*t3;
t8 = 1.0./t5;
A_min = reshape([0.0,-k_l.*m.*t4.*t8,1.0,m.*t4.*t8.*xi_l.*sqrt(k_l.*t5).*-2.0],[2,2]);
if nargout > 1
    B_min = [0.0;m.*t4.*t8];
end
if nargout > 2
    D_min = [0.0;k_l.*l_0.*m.*t4.*t8];
end
if nargout > 3
    T_coord = reshape([1.0,0.0,0.0,0.0,t7,1.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,t7,1.0],[4,4]);
end
end
