function M = massMatrix(in1,in2)
%massMatrix
%    M = massMatrix(IN1,IN2)

%    This function was generated by the Symbolic Math Toolbox version 9.3.
%    19-May-2025 16:56:37

m = in2(1,:);
m_f = in2(5,:);
t2 = -m_f;
M = reshape([m,t2,t2,m_f],[2,2]);
end
