function posMechWork = posMechWork(in1,u)
%posMechWork
%    posMechWork = posMechWork(IN1,U)

%    This function was generated by the Symbolic Math Toolbox version 9.3.
%    19-May-2025 16:56:37

dl = in1(4,:);
posMechWork = dl.*u.*(9.0./2.0e+1)+sqrt((dl.^2.*u.^2)./4.0+9.0./1.0e+2).*(1.1e+1./1.0e+1);
end
