function event_nadir = event(in1,u,in3)
%EVENT
%    EVENT_NADIR = EVENT(IN1,U,IN3)

%    This function was generated by the Symbolic Math Toolbox version 9.3.
%    23-May-2025 16:10:59

dl = in1(2,:);
event_nadir = -dl;
end
