function jump_nadir = jump(in1,u,in3)
%JUMP
%    JUMP_NADIR = JUMP(IN1,U,IN3)

%    This function was generated by the Symbolic Math Toolbox version 9.3.
%    23-May-2025 16:10:59

dl = in1(2,:);
l = in1(1,:);
jump_nadir = [l;dl];
end
