function W_S_dot = contactJacobianDerivative(in1,in2)
%contactJacobianDerivative
%    W_S_dot = contactJacobianDerivative(IN1,IN2)

%    This function was generated by the Symbolic Math Toolbox version 9.3.
%    09-Oct-2025 15:26:32

alpha = in1(4,:);
dalpha = in1(9,:);
dl = in1(10,:);
dphi = in1(8,:);
l = in1(5,:);
phi = in1(3,:);
t2 = alpha+phi;
t3 = cos(t2);
t4 = sin(t2);
t5 = dl.*t3;
t6 = dl.*t4;
t7 = dalpha.*l.*t3;
t8 = dphi.*l.*t3;
t9 = dalpha.*l.*t4;
t10 = dphi.*l.*t4;
t11 = -t9;
t12 = -t10;
t13 = t6+t7+t8;
t14 = t5+t11+t12;
W_S_dot = reshape([0.0,0.0,t14,t14,dalpha.*t3+dphi.*t3,0.0,0.0,t13,t13,dalpha.*t4+dphi.*t4],[5,2]);
end
