function W_S = contactJacobian(in1,in2)
%contactJacobian
%    W_S = contactJacobian(IN1,IN2)

%    This function was generated by the Symbolic Math Toolbox version 9.3.
%    09-Oct-2025 15:26:32

alpha = in1(4,:);
l = in1(5,:);
phi = in1(3,:);
r_f = in2(11,:);
t2 = alpha+phi;
t3 = cos(t2);
t4 = sin(t2);
t5 = l.*t3;
t6 = l.*t4;
t7 = r_f+t5;
W_S = reshape([1.0,0.0,t7,t7,t4,0.0,1.0,t6,t6,-t3],[5,2]);
end
