function M = massMatrix(in1,in2)
%massMatrix
%    M = massMatrix(IN1,IN2)

%    This function was generated by the Symbolic Math Toolbox version 9.3.
%    09-Oct-2025 15:26:31

alpha = in1(4,:);
d_f = in2(10,:);
d_l = in2(9,:);
l = in1(5,:);
m = in2(1,:);
m_f = in2(5,:);
m_l = in2(4,:);
phi = in1(3,:);
theta_f = in2(8,:);
theta_l = in2(7,:);
theta_t = in2(6,:);
t2 = d_f.*m_f;
t3 = d_l.*m_l;
t4 = alpha+phi;
t5 = l.*m_f;
t9 = cos(t4);
t10 = sin(t4);
t11 = -t2;
t12 = d_f.*t2;
t13 = d_l.*t3;
t14 = l.*t5;
t15 = l.*t2.*2.0;
t16 = m_f.*t9;
t17 = m_f.*t10;
t18 = -t15;
t20 = t3+t5+t11;
t19 = -t16;
t21 = t9.*t20;
t22 = t10.*t20;
t23 = t12+t13+t14+t18+theta_f+theta_l;
M = reshape([m,0.0,t21,t21,t17,0.0,m,t22,t22,t19,t21,t22,t23+theta_t,t23,0.0,t21,t22,t23,t23,0.0,t17,t19,0.0,0.0,m_f],[5,5]);
end
