function event_apex = event(in1,u,in3)
%EVENT
%    EVENT_APEX = EVENT(IN1,U,IN3)

%    This function was generated by the Symbolic Math Toolbox version 9.3.
%    19-May-2025 16:56:38

dy = in1(3,:);
event_apex = dy;
end
