function jump_apex = jump(in1,u,in3)
%JUMP
%    JUMP_APEX = JUMP(IN1,U,IN3)

%    This function was generated by the Symbolic Math Toolbox version 9.3.
%    19-May-2025 16:56:38

dl = in1(4,:);
dy = in1(3,:);
l = in1(2,:);
y = in1(1,:);
jump_apex = [y;l;dy;dl];
end
