function event_lo = event(in1,in2,in3)
%EVENT
%    EVENT_LO = EVENT(IN1,IN2,IN3)

%    This function was generated by the Symbolic Math Toolbox version 24.2.
%    2025-10-30 15:46:59

alpha = in1(1,:);
d_f = in3(9,:);
d_l = in3(8,:);
dalpha = in1(3,:);
dl = in1(4,:);
g = in3(2,:);
k_h = in3(14,:);
k_l = in3(15,:);
l = in1(2,:);
l_0 = in3(3,:);
m = in3(1,:);
m_f = in3(5,:);
m_l = in3(4,:);
phi_0 = in3(11,:);
r_f = in3(10,:);
theta_f = in3(7,:);
theta_l = in3(6,:);
u_h = in2(1,:);
u_l = in2(2,:);
xi_h = in3(12,:);
xi_l = in3(13,:);
t2 = alpha+phi_0;
t3 = alpha.*2.0;
t4 = d_f.^2;
t5 = d_l.^2;
t6 = dalpha.^2;
t7 = l.^2;
t8 = l_0.^2;
t9 = m_f.^2;
t10 = m_l.^2;
t12 = r_f.^2;
t15 = -m_f;
t19 = d_f.*l_0.*m_f.*2.0;
t13 = cos(t2);
t14 = sin(t2);
t16 = m_f.*t4;
t17 = m_l.*t5;
t18 = m_f.*t8;
t20 = m+t15;
t21 = t2.*2.0;
t22 = cos(t21);
t23 = sin(t21);
t24 = k_l.*t20;
t26 = t16+t17+t18+t19+theta_f+theta_l;
t25 = sqrt(t24);
t27 = k_h.*t26;
t28 = sqrt(t27);
et1 = l.^3.*t13.*t24.*-2.0+g.*m.*t16+g.*m.*t17+g.*m_f.*t17+g.*m.*theta_f+g.*m.*theta_l+g.*m_f.*theta_f+g.*m_f.*theta_l-g.*t5.*t10-g.*t7.*t9.*2.0-r_f.*t7.*t24.*3.0+t13.*t16.*u_l.*2.0+t13.*t17.*u_l.*2.0+t13.*theta_f.*u_l.*2.0+t13.*theta_l.*u_l.*2.0+d_f.*g.*l.*t9.*2.0+g.*m.*m_f.*t7.*2.0+g.*m.*m_f.*t12.*2.0+d_f.*m_f.*r_f.*u_l.*3.0-d_l.*m_l.*r_f.*u_l.*3.0-d_f.*m_f.*t14.*u_h.*2.0+d_l.*m_l.*t14.*u_h.*2.0-g.*m.*t17.*t22+g.*m_f.*t17.*t22-g.*m.*t22.*theta_f-g.*m.*t22.*theta_l+g.*m_f.*t22.*theta_f+g.*m_f.*t22.*theta_l+l.*l_0.*r_f.*t24.*3.0-k_l.*l.*t13.*t16.*2.0-k_l.*l.*t13.*t17.*2.0+k_l.*l_0.*t13.*t16.*2.0+k_l.*l_0.*t13.*t17.*2.0-k_l.*l.*t13.*theta_f.*2.0-k_l.*l.*t13.*theta_l.*2.0;
et2 = k_l.*l_0.*t13.*theta_f.*2.0+k_l.*l_0.*t13.*theta_l.*2.0+l.*m.*r_f.*u_l.*3.0-l.*m_f.*r_f.*u_l.*3.0-l.*m.*t14.*u_h.*2.0+l.*m_f.*t14.*u_h.*2.0+g.*t4.*t9.*t22.*2.0+g.*t5.*t10.*t22-l.*t12.*t13.*t24.*2.0+l_0.*t7.*t13.*t24.*2.0+l_0.*t12.*t13.*t24.*2.0-m.*r_f.*t23.*u_h+m_f.*r_f.*t23.*u_h+m.*t7.*t13.*u_l.*2.0+m.*t12.*t13.*u_l.*2.0-m_f.*t7.*t13.*u_l.*2.0-r_f.*t4.*t6.*t9.*3.0-r_f.*t7.*t22.*t24-d_f.^3.*t6.*t9.*t13.*2.0+d_f.*d_l.*g.*m_f.*m_l.*2.0-d_f.*g.*l.*m.*m_f.*2.0-d_l.*g.*l.*m_f.*m_l.*4.0-alpha.*d_l.*k_h.*m_l.*t14.*2.0-alpha.*k_h.*l.*m_f.*t14.*2.0-d_f.*k_l.*l.*m_f.*r_f.*3.0+d_l.*k_l.*l.*m_l.*r_f.*3.0+d_f.*k_l.*l_0.*m_f.*r_f.*3.0-d_l.*k_l.*l_0.*m_l.*r_f.*3.0-dalpha.*dl.*m.*t14.*t16.*4.0;
et3 = dalpha.*dl.*m.*t14.*t17.*-4.0+dalpha.*dl.*m_f.*t14.*t17.*4.0-dalpha.*dl.*m.*t14.*theta_f.*4.0-dalpha.*dl.*m.*t14.*theta_l.*4.0+dalpha.*dl.*m_f.*t14.*theta_f.*4.0+dalpha.*dl.*m_f.*t14.*theta_l.*4.0-d_f.*g.*l.*t9.*t22.*2.0+alpha.*k_h.*m.*r_f.*t23+dalpha.*dl.*t4.*t9.*t14.*4.0+dalpha.*dl.*t5.*t10.*t14.*4.0+dalpha.*dl.*t9.*t12.*t14.*4.0+d_f.*k_h.*m_f.*t3.*t14+d_l.*k_l.*m_l.*t7.*t13.*4.0+d_f.*g.*r_f.*t9.*t13.*4.0-d_l.*l.*m_l.*t13.*u_l.*4.0+alpha.*k_h.*r_f.*t15.*t23+d_f.*l.*r_f.*t6.*t9.*3.0+k_h.*l.*m.*t3.*t14-k_l.*l.*m_f.*t12.*t13.*2.0+k_l.*l_0.*m_f.*t12.*t13.*2.0-g.*l.*r_f.*t9.*t13.*4.0+d_f.*m_f.*r_f.*t22.*u_l-d_l.*m_l.*r_f.*t22.*u_l-d_f.*m_f.*t6.*t13.*t17.*2.0-d_f.*m_f.*t6.*t13.*theta_f.*2.0-d_f.*m_f.*t6.*t13.*theta_l.*2.0+g.*m.*t4.*t15.*t22+l.*l_0.*r_f.*t22.*t24;
et4 = d_f.*t6.*t7.*t9.*t13.*2.0+l.*m.*r_f.*t22.*u_l-dl.*t13.*t16.*t25.*xi_l.*4.0-dl.*t13.*t17.*t25.*xi_l.*4.0-dl.*t13.*t25.*theta_f.*xi_l.*4.0-dl.*t13.*t25.*theta_l.*xi_l.*4.0+l.*r_f.*t15.*t22.*u_l-r_f.*t4.*t6.*t9.*t22+dalpha.*m.*r_f.*t23.*t28.*xi_h.*2.0-dalpha.*m_f.*r_f.*t23.*t28.*xi_h.*2.0-dl.*m.*t7.*t13.*t25.*xi_l.*4.0-dl.*m.*t12.*t13.*t25.*xi_l.*4.0+dl.*m_f.*t7.*t13.*t25.*xi_l.*4.0-d_f.*d_l.*g.*m_f.*m_l.*t22.*2.0-d_f.*dalpha.*dl.*l.*t9.*t14.*4.0+d_f.*g.*l.*m.*m_f.*t22.*2.0+d_f.*dalpha.*dl.*r_f.*t9.*t23.*2.0-d_l.*k_l.*l.*l_0.*m_l.*t13.*4.0+d_f.*d_l.*m_f.*m_l.*r_f.*t6.*3.0-dalpha.*dl.*m.*m_f.*t12.*t14.*4.0-d_l.*g.*m_f.*m_l.*r_f.*t13.*4.0+d_l.*k_l.*l.*m_l.*r_f.*t22+d_f.*k_l.*l_0.*m_f.*r_f.*t22-d_l.*k_l.*l_0.*m_l.*r_f.*t22;
et5 = d_f.*l.*m.*m_f.*r_f.*t6.*-3.0+g.*l.*m.*m_f.*r_f.*t13.*4.0-d_f.*dl.*m_f.*r_f.*t25.*xi_l.*6.0+d_l.*dl.*m_l.*r_f.*t25.*xi_l.*6.0+d_f.*k_l.*l.*r_f.*t15.*t22+d_f.*dalpha.*m_f.*t14.*t28.*xi_h.*4.0-d_l.*dalpha.*m_l.*t14.*t28.*xi_h.*4.0-d_f.*m.*m_f.*t6.*t7.*t13.*2.0-d_f.*m.*m_f.*t6.*t12.*t13.*2.0-dl.*l.*m.*r_f.*t25.*xi_l.*6.0+dl.*l.*m_f.*r_f.*t25.*xi_l.*6.0+dalpha.*l.*m.*t14.*t28.*xi_h.*4.0-dalpha.*l.*m_f.*t14.*t28.*xi_h.*4.0+d_f.*l.*r_f.*t6.*t9.*t22-d_f.*d_l.*dalpha.*dl.*m_f.*m_l.*t14.*4.0+d_f.*dalpha.*dl.*l.*m.*m_f.*t14.*4.0-d_f.*dalpha.*dl.*m.*m_f.*r_f.*t23.*2.0+d_f.*d_l.*l.*m_f.*m_l.*t6.*t13.*4.0+d_f.*d_l.*m_f.*m_l.*r_f.*t6.*t22+d_l.*dl.*l.*m_l.*t13.*t25.*xi_l.*8.0-d_f.*dl.*m_f.*r_f.*t22.*t25.*xi_l.*2.0+d_l.*dl.*m_l.*r_f.*t22.*t25.*xi_l.*2.0+d_f.*l.*m.*r_f.*t6.*t15.*t22;
et6 = dl.*l.*m.*r_f.*t22.*t25.*xi_l.*-2.0+dl.*l.*m_f.*r_f.*t22.*t25.*xi_l.*2.0;
event_lo = (et1+et2+et3+et4+et5+et6)./(t16.*2.0+t17.*2.0+theta_f.*2.0+theta_l.*2.0+m.*t7.*2.0+m.*t12-m_f.*t7.*2.0+m_f.*t12-d_l.*l.*m_l.*4.0+m.*t12.*t22+t12.*t15.*t22+d_f.*m_f.*r_f.*t13.*4.0-d_l.*m_l.*r_f.*t13.*4.0+l.*m.*r_f.*t13.*4.0-l.*m_f.*r_f.*t13.*4.0);
end
