function jump_noX = jump_noX(in1,in2,in3)
%jump_noX
%    jump_noX = jump_noX(IN1,IN2,IN3)

%    This function was generated by the Symbolic Math Toolbox version 24.2.
%    2025-10-30 15:47:00

alpha = in1(1,:);
dalpha = in1(3,:);
dl = in1(4,:);
l = in1(2,:);
phi_0 = in3(11,:);
r_f = in3(10,:);
t2 = alpha+phi_0;
t3 = cos(t2);
t4 = sin(t2);
t5 = l.*t3;
t6 = r_f+t5;
jump_noX = [0.0;t6;alpha;l;-dalpha.*t6-dl.*t4;dl.*t3-dalpha.*l.*t4;dalpha;dl];
end
