function jump_lo = jump(in1,in2,in3,x0,alpha0,l0)
%JUMP
%    JUMP_LO = JUMP(IN1,IN2,IN3,X0,ALPHA0,L0)

%    This function was generated by the Symbolic Math Toolbox version 24.2.
%    2025-10-30 15:47:00

alpha = in1(1,:);
dalpha = in1(3,:);
dl = in1(4,:);
l = in1(2,:);
phi_0 = in3(11,:);
r_f = in3(10,:);
t2 = alpha+phi_0;
t3 = alpha0+phi_0;
t4 = cos(t2);
t5 = sin(t2);
t6 = l.*t4;
t7 = r_f+t6;
jump_lo = [x0-l.*t5-r_f.*t2+r_f.*t3+l0.*sin(t3);t7;alpha;l;-dalpha.*t7-dl.*t5;dl.*t4-dalpha.*l.*t5;dalpha;dl];
end
