function out1 = masses(in1)
%MASSES
%    OUT1 = MASSES(IN1)

%    This function was generated by the Symbolic Math Toolbox version 24.2.
%    2025-10-30 15:47:00

m = in1(1,:);
m_f = in1(5,:);
m_l = in1(4,:);
out1 = [m-m_f-m_l,m_l,m_f];
end
