function threeBodiesAccjac_Y = threeBodiesAccjac_Y(in1,in2)
%threeBodiesAccjac_Y
%    threeBodiesAccjac_Y = threeBodiesAccjac_Y(IN1,IN2)

%    This function was generated by the Symbolic Math Toolbox version 24.2.
%    2025-10-30 15:47:00

alpha = in1(1,:);
d_f = in2(9,:);
d_l = in2(8,:);
dalpha = in1(3,:);
dl = in1(4,:);
l = in1(2,:);
phi_0 = in2(11,:);
t2 = alpha+phi_0;
t5 = -l;
t3 = cos(t2);
t4 = sin(t2);
t10 = d_f+t5;
t6 = l.*t3;
t7 = dalpha.*t4;
t8 = dl.*t4;
t13 = t4.*t5;
t11 = -t7;
t12 = -t8;
threeBodiesAccjac_Y = reshape([t12+dalpha.*t3.*t5,t12+dalpha.*(d_l.*t3+t3.*t5),-dalpha.*(t6+t3.*t10),t11,t11,0.0,t13,t13+d_l.*t4,t13-t4.*t10,t3,t3,0.0],[3,4]);
end
